# Generated by Django 2.2.4 on 2019-08-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('roles', '0002_medico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Paciente',
        ),
    ]
